const INVENTORY_CREATE = 'CREATE';
const INVENTORY_UPDATE = 'UPDATE';
const INVENTORY_DELETE = 'DELETE';
const INVENTORY_FLUSH = 'FLUSH';
const CURRENT_PRODUCT_INCRIMENT = 'CURRENT_PRODUCT_INCRIMENT';
const CURRENT_PRODUCT_DECRIMENT = 'CURRENT_PRODUCT_DECRIMENT';
const CURRENT_PRODUCT_UPDATE = 'CURRENT_PRODUCT_UPDATE';
const SET_CURRENT_PRODUCT_CODE = 'SET_CURRENT_PRODUCT_CODE';
const SET_CURRENT_PRODUCT_PRICE = 'SET_CURRENT_PRODUCT_PRICE';
const SET_CURRENT_PRODUCT_AMOUNT = 'SET_CURRENT_PRODUCT_AMOUNT';
const SET_CURRENT_PRODUCT_MEASUREMENT = 'SET_CURRENT_PRODUCT_MEASUREMENT';

const actionTypes = {
    INVENTORY_CREATE,
    INVENTORY_UPDATE,
    INVENTORY_DELETE,
    INVENTORY_FLUSH,
    CURRENT_PRODUCT_INCRIMENT,
    CURRENT_PRODUCT_DECRIMENT,
    CURRENT_PRODUCT_UPDATE,
    SET_CURRENT_PRODUCT_CODE,
    SET_CURRENT_PRODUCT_PRICE,
    SET_CURRENT_PRODUCT_AMOUNT,
    SET_CURRENT_PRODUCT_MEASUREMENT,
};

export default actionTypes;